
name: qqq
description: A Flutter movie app using SQLite for user authentication and TMDB API integration.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  provider: ^6.0.0
  url_launcher: ^6.0.9
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.15
  carousel_slider: ^5.0.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
